### ISSUE TITLE
The display of text, line, and arrow on the left side of the Lifeline is incorrect.

### ISSUE THREAD

**Issue by devwitalik** [plantuml/plantuml#1683] opened 2024-02-10 23:06 UTC
```plantuml
@startuml
skinparam {
   Maxmessagesize 200
}

activate Test
Test <<-- Test : the arrow and text are located inside the Lifeline because they are counted from the right side of the active member's column bar (Lifeline). Which is an incorrect display, right?
Test <<-- Test : also the arrow is not displayed correctly (issue: #1678). (I wonder if the closing of the Lifeline is displayed correctly? Should it also include the arrow before it, i.e. close after it? If not, how do I close the Life Line after the last arrow?)
deactivate Test

@enduml
```
http://www.plantuml.com/plantuml/uml/RP5DwnCn4CRl-HGFUB1_Q4lre58Assj1JmgUPvFPxc1UIYQnhU9tTpTjfQANm0o_vsN8NWlbKeCt-atYYJ85_3G0Fj4bi2eTMUK7u-rcOtuPGxR8TogCBwp5p0zskzMgZTYYZ0pAEPr1qQ7mfKmZmoSxQHmagZXkr4SPs4jaz6ofQbjU6snJZJCyv1GQckKu5ZHb6jgcjM043Ztdrpf9V0qHFMKi7iOlQtmTnOuG1KL8j2bdjWLEzEJfkhpvTlyUGLxJqoMYYEcFZ1tkHlwAXQXMtkBLctVlFqo1YmFEAJhEa5jHwvDAFBRUpqUB_i-lm-SnLUyWfPMOI_lg-AbCpqFAF05Bo9hNBO11GvapIuV3C9TTOfnObt2u0u_mwObtlEqyQRavTo_6yT-_Q_OSNGt-Dm00

**Screenshots**
![IMG](http://www.plantuml.com/plantuml/png/RP5DYnD148RlyojUy60MTaFqe182asj0JmgUQxfhCeNz4RgwJQBut-tq99BWNXggvda_YjbgffIBTvt-a72WH1w_Em1VwEHPbVQiyelnVhNg_dGTcIm_AJE-iURkyc2pUNbf8zR84uDIYaTGiCXyodLak6YgnaA2YkL6VPQHdGJ6m8QAjkMvmIQMS87757r3a-odZAQCOzkq5WpFVk3qLgl45HymKCBYPloqnFT9p0HHK8044rDYas553uxEpxDl__yHv3JUNLBr8VwJiSNLo9sn4DN2Qxnvz-7ZfngusE4OW-K4cOiQ5rN27d5yF5hqDRyUNwTOd8NakKGjxOhbkp83Zp5n1PuXIrws00QD-PAPU-n6X5W_JfMr4RihS0klJxZYRUT8y-pSFtMM7__kbeCjtlq5)

**Comment by jimnelson372** [comment] 2024-05-16 22:17
I am examining the code to see what can be done here.  I just recently fixed some other problems related to left side self messages, but those fixes didn't address the active lifeline conditions.  (See #1777.)

In your example, the positioning is definitely wrong.  However, one of the effect you asked about parenthetically isn't wrong:

> (I wonder if the closing of the Lifeline is displayed correctly? Should it also include the arrow before it, i.e. close after it? If not, how do I close the Life Line after the last arrow?)

Closing the lifeline by the end of the self message is caused by the "deactivate" statement immediately following that arrow.  It's easier to see on the Right side self arrows, since they are drawn in the correct position, but instead of using that "deactivate" as you're doing here, leave it out and you'll get:

![testpuml_002](https://github.com/plantuml/plantuml/assets/66284321/07e65225-bf85-4579-9327-458ce2891c49)


Where the lifeline continues on, just as in the first case.   To explicitly have the self message cause the deactivation, you can also use --: just before the comment, rather than just : .  It's easier, as I said, to see on the Right side.

Here is a test script:

```
@startuml
Test -> Test : 1st self message, no activation
Test -> Test ++: 2nd self message, starting activation
Test -> Test ++: 3rd self message, staring another activation
Test -> Test : 4th self message, continuing in the current activation
Test -> Test --: 5th self message, deactivating once
Test -> Test : 6th self message, continuing the activation
Test -> Test --: 7th self message, exiting the activation
Test -> Test : 8th self message, no activation
@enduml
```
Which generates:

![testpuml_003](https://github.com/plantuml/plantuml/assets/66284321/aaecffcc-6778-426f-9ca0-c8defd2b3e3b)

Unfortunately, the bug with the positioning on the left side during active timelines makes this look a mess, if we switch to left side self messages:

![testpuml_004](https://github.com/plantuml/plantuml/assets/66284321/0d0fcb30-87ba-42ca-9a29-7a010a73a655)

I'm glad you asked about the ending of the timeline, though, since I initially thought I would need to change the vertical positioning.  But when double checking the documentation, I saw examples (for the right side) similar to what I shared above.

I hope to have a solution for the left side positioning soon.

Regards,
Jim Nelson

**Comment by arnaudroques** [comment] 2024-05-17 09:02
@jimnelson372 

It’s great to see the progress you’re making on this issue.

I’d like to mention that we currently have two algorithms in use: "puma" and "teoz." "Puma" is quite old and notoriously difficult to fix. While it would be beneficial if you manage to address the issue with "puma," please be aware that our long-term goal is to have these issues resolved in "teoz." (see https://plantuml.com/teoz )

Eventually, we plan to decommission "puma" once "teoz" is fully operational and can handle all scenarios. 

Thank you again for your efforts!

**Comment by jimnelson372** [comment] 2024-05-17 21:52
Understood, @arnaudroques.   

Fortunately, my focus to start was on drawing code common to both "teoz" and "puma" for these left directed self messages.  While many changes were required in the common drawing code for these left side self messages, I did have to make changes to the self message class in "teoz" and had that version working first.  Then I found how I could make the "puma" prepare the same conditions that drawing class needed.  So both are fixed.  I'm preparing the pull request.

Here's what the first script in this issue now produces.  I left the text as given, even though it's no longer having the problems the text message says it is having.  First in puma (which was the example).

![testleftactive](https://github.com/plantuml/plantuml/assets/66284321/e452459e-418b-4544-9284-c7e6560049d3)

But, here it is with teoz turn on:

![testleftactive](https://github.com/plantuml/plantuml/assets/66284321/aaac8c80-d6b2-42c7-98e9-e8b4a2896352)

A slightly modified version of my own script above (with a step 2.5, and with the text and arrows in green so I can tell where they may overlap the timeline) now looks like this, first in "puma":

![testleftactive](https://github.com/plantuml/plantuml/assets/66284321/d7b69c92-2d51-416d-a6fa-e8d44bd94398)

And it works equally well in "teoz":

![testleftactive](https://github.com/plantuml/plantuml/assets/66284321/2af7758f-ee28-4171-968c-efe450321db1)

And here is "teoz" with the rose skin chosen:

![testleftactive](https://github.com/plantuml/plantuml/assets/66284321/423d7a29-1b1a-4451-9f48-81d5b9881445)

You can see that I have left the drawing of the active levels alone, letting them increase to the right.  After all, there can be a mix of left side and right side messages so it was best to leave the time line drawing along and just have the left side self messages do what was appropriate for them.    

These left side self messages now leave the active level they belong to and enter back at the appropriate active level.  Also, it was intentional for that message labeled 4th to start and end from the left side of that second activation group, while keeping its text from moving further right.One of the tricks was for the 0 level to 1 level to have a longer upper line while moves from level 1 to 2 and so on have longer lower lines.   And the 1 back to 0 must be drawn differently than the 2 back 1, etc.   Some of these differences from how the right side self messages work is what took me a little longer to account for in my fix.

I look forward to finishing the pull request.

Regards,
Jim Nelson

**Comment by jimnelson372** [comment] 2024-05-17 22:11
...Though I have not yet addressed the left side arrow head issue mentioned in the first example, and also issue: #1678.  I'm looking at that now.

**Comment by jimnelson372** [comment] 2024-05-19 23:46
I just posted examples of all the arrow styles working for left side self messages over in the comments for issue #1678.   Here's one image from that post, from my current fix that I am working on:

![testarrows2_002](https://github.com/plantuml/plantuml/assets/66284321/d1b6f804-bfab-421e-8b87-218a1334de31)


I ask a final question there that hopefully someone can answer.  It's related to "x<-" and "<-x", which seems to have a bug, but I'm not sure the intent.  Since X arrows are not directly about left side self messages, perhaps even if my question results in a change request, that could be left for a future issue. 

Regards,
Jim

**Closed** 2024-05-28 05:43 UTC
Labels: triage
