### ISSUE TITLE
MindMap Diagram Support!

### ISSUE THREAD

**Issue by aadrian** [plantuml/plantuml#43] opened 2017-03-15 13:41 UTC
Hi,

Please add MindMap Diagram Support too :) .

Something compact like FreePlane https://sourceforge.net/projects/freeplane/ is producing: http://freeplane.sourceforge.net/wiki/index.php/File:FreeplaneWiki.jpg  would be very useful.

Thanks in advance.

**Comment by kiebor** [comment] 2017-06-23 23:24
I second this request. It would be a valuable edition for early inception of customer requirements.

**Comment by rezarahimi** [comment] 2018-01-21 20:20
I find this feature very useful and valuable.

**Comment by chen56** [comment] 2018-07-11 03:30
plan?

**Comment by HabibMAALEM** [comment] 2018-08-13 12:46
+1

**Comment by EtienneK** [comment] 2018-10-09 08:34
+1

**Comment by balancin** [comment] 2018-11-04 05:11
+1 !

**Comment by everdom** [comment] 2018-11-09 10:05
+1

**Comment by fcu-d0449763** [comment] 2018-11-09 15:14
+1

**Comment by arunkhattri** [comment] 2018-11-15 05:11
+1

**Comment by olkobg** [comment] 2018-12-19 16:38
+1

**Comment by dinosaurkfb** [comment] 2019-01-22 03:04
+1

**Comment by alex1a** [comment] 2019-01-22 17:42
+1

**Comment by novoid** [comment] 2019-01-22 19:08
Please can we _stop_ adding pointless "+1" comments here that spam all people who are watching this issue?

Add a +1 emoji to the topmost comment instead to express your support. This also prevents "information fragmentation" among comments and emoji reactions.

**Comment by arnaudroques** [comment] 2019-01-22 22:18
Ok, since this is very popular, we have created a page here http://wiki.plantuml.net/site/mindmap
On this page, we expect people to propose a simple syntax and some images.
Once the design will be fixed, we will see how implement it.

**Comment by pinage404** [comment] 2019-02-15 22:20
As a first step, i would like to have a very simple syntax (more options could be added later), something like this :

```markdown
* root node
	* some first level node
		* second level node
		* another second level node
	* another first level node
```

That would generate something like this :

![14795e60316f11e98b7eb99c51ab8a47 map](https://user-images.githubusercontent.com/6325757/52887314-927c4e00-3177-11e9-904e-9ba120d0dd16.png)

(Done with MindMup)

**Comment by novoid** [comment] 2019-02-16 12:45
> As a first step, i would like to have a very simple syntax (more options could be added later), something like this [...]

Thanks for the first syntax proposal.

Instead of introducing a new syntax (at least I do think this is not some common markup language syntax), I'd suggest to use any given syntax. I personally do have [preference for Org mode syntax](https://karl-voit.at/2017/09/23/orgmode-as-markup-only/).

With this, your example would look like:

```
* root node
** some first level node
**** second level node
**** another second level node
** another first level node
```

The advantage of Org mode would also be that there is the possibility to add links between the nodes and a ton of cool stuff later on, if necessary: https://orgmode.org/worg/dev/org-syntax.html

**Comment by pinage404** [comment] 2019-02-17 11:15
My syntax proposition is compatible with Markdown nested lists

I don't know the Org Mode syntax, yet ; but it seems simple too =)

I'm really impatient to have this feature

**Comment by arnaudroques** [comment] 2019-02-17 22:04
Ok, thanks for all your suggestions.
This is more an alpha version, but with last beta http://beta.plantuml.net/plantuml.jar you can have
```
@startmindmap
* root node
** some first level node
*** second level node
*** another second level node
** another first level node
@endmindmap
```
The drawing is far from perfect (no link, only basic layout...) but we are working hard on it.
After all this time, we just want to let you know that we have started something !

**Comment by swmatisa** [comment] 2019-02-18 11:07
Thanks for this  first step. The png is one pixel too narrow and one pixel not high enough.

It is OK with svg

**Comment by arnaudroques** [comment] 2019-02-18 22:02
We have added links drawing in last beta http://beta.plantuml.net/plantuml.jar
There are still some pixels error, we will fix them in the incoming days.
We have updated http://wiki.plantuml.net/site/mindmap page with some other syntaxes that are all working with current beta. The idea is to let people play with different syntaxes to let new ideas emerge...
You can post your suggestions either in this post or in the wiki.
Thanks for your help!

**Comment by pinage404** [comment] 2019-02-18 22:20
Great work ! @arnaudroques 

Same problème as @swmatisa, the png is a bit cropped

The SVG seems good

<details>
<summary>I wrote a ~~ugly~~ _simple_ Python 3 script to help me generate some cases</summary>

```python=3
#!/usr/bin/env python3
import sys

def deep(width, depth, previous_level_star='*', previous_level_label=''):
    if depth < 0:
        return

    for index in range(1, width + 1):
        level_star = previous_level_star + '*'
        level_label = previous_level_label + str(index)

        print('%s %s' % (level_star, level_label))

        deep(width, depth - 1, level_star, level_label)


def generate_mindmap(width, depth):
    print('@startmindmap')
    print('* root')
    deep(width, depth)
    print('@endmindmap')


try:
    width = int(sys.argv[1])
    depth = int(sys.argv[2])

    generate_mindmap(width, depth)
except (ValueError, IndexError):
    print('USAGE: %s WIDTH DEPTH' % sys.argv[0])
```

</details>

---

Here is all my tests, i hope that can help you

---

This one gave me `error42` :warning: 

```sh
./deep.py 2 2 > map.puml
```

```plantuml
@startmindmap
* root
** 1
*** 11
**** 111
**** 112
*** 12
**** 121
**** 122
** 2
*** 21
**** 211
**** 212
*** 22
**** 221
**** 222
@endmindmap
```

---

Multiroot displayed the last root with his branch (:warning: i don't know how it should behave)

```plantuml
@startmindmap
* First Root
** With some branch
* Second Root
** With another branch
@endmindmap
```

---

Option worked :ok_hand: 

```plantuml
@startmindmap
scale 2

* Option
@endmindmap
```

---

Comment worked :ok_hand: 

```plantuml
@startmindmap
* Root
' * Comment
@endmindmap
```

---

Deep map worked :ok_hand: 

```sh
./deep.py 1 100 > map.puml
```

---

No root gave me a `Syntax Error?` :ok_hand: 

```plantuml
@startmindmap
@endmindmap
```

---

Empty node gave me a `Syntax Error?` :ok_hand: 

```plantuml
@startmindmap
* Root
* 
@endmindmap
```

---

Missing level gave me a `Syntax Error?` :ok_hand:

```plantuml
@startmindmap
* first
*** third
@endmindmap
```

---

Two branches with the same name gave me two branches with the same name :ok_hand: 

```plantuml
@startmindmap
* root
** two branches with the same name
** two branches with the same name
@endmindmap
```

**Comment by arnaudroques** [comment] 2019-02-19 16:16
Many thanks for your tests : it really helps !
png should be ok with last beta http://beta.plantuml.net/plantuml.jar (beta12)
Few other things are working better also, but there are still some work to be done.

**Comment by pinage404** [comment] 2019-02-20 22:52
I don't find recent commits related to the MindMap https://github.com/plantuml/plantuml/commits/master

**Comment by pinage404** [comment] 2019-02-20 23:51
Tested with beta version download at 22:57:00 GMT

Now, there is links between nodes, it's great \o/

---

No node gave me `Empty description`
:warning:  i think this is not the most explicit error

```plantuml
@startmindmap
@endmindmap
```

---

No node with description generate nothing :warning:

```plantuml
@startmindmap "no empty description"
@endmindmap
```

---

Missing branch gave me `error42` :warning: 

```plantuml
@startmindmap
0 root
1> 1
3> 3
@endmindmap
```

---

Missing branch with other syntax gave me `error42` :warning: (same issue as above)

```plantuml
@startmindmap
* root
*> 1
*>>> 3
@endmindmap
```

---

Previously, this didn't work ; now, it works :ok_hand: 

```shell
./deep.py 2 2 > map.puml
```

```
@startmindmap
* root
** 1
*** 11
**** 111
**** 112
*** 12
**** 121
**** 122
** 2
*** 21
**** 211
**** 212
*** 22
**** 221
**** 222
@endmindmap
```

---

Multiroot display an appropriate message :ok_hand: 

```plantuml
@startmindmap
* First Root
** With some branch
* Second Root
** With another branch
@endmindmap
```

---

Mixing the syntaxes works :ok_hand: 

```plantuml
@startmindmap
0 root
** 1
2> 2
**** 3
*>>>> 4
@endmindmap
```

**Comment by arnaudroques** [comment] 2019-02-22 21:04
With last beta http://beta.plantuml.net/plantuml.jar you can remove the box drawing:

```
@startmindmap
0 root node
1> some first level node
2>_ second level node
2>_ another second level node
2>_ foo
2>_ bar
2>_ foobar
1> another first level node
@endmindmap
```

We have also slightly enhanced the link drawing.
All these will be integrated in next official release beginning of March.

**Comment by pinage404** [comment] 2019-02-23 13:07
Nice !

OrgMode syntax with dash doesn't work `Syntax Error?` :warning:

```plantuml
@startmindmap
0 root node
**_ bar
1>_ foo
*>_ foobar
@endmindmap
```

**Comment by pinage404** [comment] 2019-02-23 13:33
Empty mindmap generate a file with the given name (`not an empty description.png` in this case) but with the error `Empty description` :warning: the help message message is wrong

```plantuml
@startmindmap "not an empty description"
@endmindmap
```

**Comment by pinage404** [comment] 2019-02-24 12:17
`header` and `footer` are not generated :warning: 

```plantuml
@startmindmap
* root

header
My super header
endheader

center footer My super footer
@endmindmap
```

---

Same problem for `title` :warning: 

```plantuml
@startmindmap
* root

title My super title
@endmindmap
```

---

Same for `caption` :warning: 

```plantuml
@startmindmap
* root

caption figure 1
@endmindmap
```

---

Idem for `legend` :warning: 

```plantuml
@startmindmap
* root

legend top left
  Short
  legend
endlegend

legend right
  Short
  legend
endlegend
@endmindmap
```

---

Skin Param seems to doesn't work too :warning: 

```plantuml
@startmindmap
skinparam monochrome true

* root
** first
** second
@endmindmap
```

```plantuml
@startmindmap
skinparam monochrome reverse

* root
** first
** second
@endmindmap
```

```plantuml
@startmindmap
skinparam backgroundColor #EEEBDC
skinparam handwritten true

* root
** first
** second
@endmindmap
```

---

Links work :ok_hand:

```plantuml
@startmindmap
* root
** first
** [[http://plantuml.com PlantUML is cool]]
@endmindmap
```

**Comment by pinage404** [comment] 2019-02-24 15:29
Opinion :

I don't like number syntax because it's more difficult to understand / visualize by simply reading the text file

```plantuml
@startmindmap "number syntax"
0 Linux
1> NixOS
1> Debian
2> Ubuntu
3> Linux Mint
3> Kubuntu
3> Lubuntu
3> KDE Neon
2> LMDE
2> SolydXK
2> SteamOS
2> Raspbian
3> <s>Raspmbc</s> => OSMC
3> <s>Raspyfi</s> => Volumio
@endmindmap
```

I prefer the OrgMode syntax, it's more verbose but easier to see the levels

```plantuml
@startmindmap "OrgMode"
* Linux
** NixOS
** Debian
*** Ubuntu
**** Linux Mint
**** Kubuntu
**** Lubuntu
**** KDE Neon
*** LMDE
*** SolydXK
*** SteamOS
*** Raspbian
**** <s>Raspmbc</s> => OSMC
**** <s>Raspyfi</s> => Volumio
@endmindmap
```

Or better yet, the Markdown syntax (which is not implemented yet) which is really easy to read and understand the levels

```plantuml
@startmindmap "Markdown"
* Linux
	* NixOS
	* Debian
		* Ubuntu
			* Linux Mint
			* Kubuntu
			* Lubuntu
			* KDE Neon
		* LMDE
		* SolydXK
		* SteamOS
		* Raspbian
			* <s>Raspmbc</s> => OSMC
			* <s>Raspyfi</s> => Volumio
@endmindmap
```

**Comment by arnaudroques** [comment] 2019-02-25 21:24
With last beta http://beta.plantuml.net/plantuml.jar you can now have:

```
@startmindmap
caption figure 1
title My super title

* count
*< 100
*<< 101
*<< 102
*< 200
*> A
*>> AA
*>> AB
*> B

header
My super header
endheader

center footer My super footer
@endmindmap
```

and

```
@startmindmap
* root node
	* some first level node
		* second level node
		* another second level node
	* another first level node
@endmindmap
```

and 

```
@startmindmap
skinparam backgroundColor #EEEBDC
skinparam handwritten true
skinparam monochrome true

* root
** first
** second
@endmindmap
```

Still interested in feedback :-)

**Comment by swmatisa** [comment] 2019-02-26 08:28
Thanks for the news. I do some tests:
- Mindmap on both side of root is very nice
- Sprite and http link in nodes: OK
- newpage: not implemented but would be nice

**Different syntaxes:**
- *<: nice, but only the first level need the direction. If we change the first level all (error42L if not coherent).
- OrgMode: very simple and can be extended
- Markdown: simple and can be extended

**Proposal**:
Add [] or{} to OrgMode and markdown syntax to:
- Add direction like *< syntax
- Add the possibility to put a text on the link
- Add the possibility to give an arrow
- Add the possibility to give an alias to a node (for future use like a "free" link between nodes)
- Add other params
Ex :
** [Direction="left", Arrow=".>", Alias="theAlias", FontSize="33"] node text

**Conclusion**:
- Syntax OrgMode(or Markdown) with param[] or {} prefered to *<
- Thanks for your last beta features

**Comment by arnaudroques** [comment] 2019-03-01 22:25
We've just published the first official release with mindmap support.
The doc is really minimal http://plantuml.com/en/mindmap-diagram
You can contribute here http://wiki.plantuml.net/site/mindmap-diagram

The syntax is not stable yet, we are going to work on @swmatisa suggestion.
We are also going to implement Work Breakdown Structure diagram (see http://forum.plantuml.net/9060/wbs-diagrams )
Somehow, there are connection between Mindmap diagram and WBS diagram...

**Comment by pinage404** [comment] 2019-03-01 22:34
Awesome !!!

---

I have this mindmap with buble that overlap other bubble

```plantuml
@startmindmap "weird"
* root
	* Lorem ipsum dolor sit amet
		* Lorem ipsum dolor sit amet
		* Lorem ipsum dolor sit amet
		* Lorem ipsum dolor sit amet
		* Lorem ipsum dolor sit amet
	* Lorem ipsu dolor sit amet
		* ---
			* ---
@endmindmap
```

![weird](https://user-images.githubusercontent.com/6325757/53670270-67672380-3c7a-11e9-97e0-f41c6e625857.png)

**Comment by pinage404** [comment] 2019-03-01 23:02
> *<: nice, but only the first level need the direction. If we change the first level all (error42L if not coherent).

I agree with @swmatisa 

Currently we can write this :

```plantuml
@startmindmap "tmp/current"
* middle
	*< middle left
		*<< left
	*> middle right
		*>> right
@endmindmap
```

Which looks like this :

![current](https://user-images.githubusercontent.com/6325757/53671310-148f6b00-3c7e-11e9-9ed1-cb6499470a17.png)


I would like to have something like this (currently, that give an `error42L`) :

```plantuml
@startmindmap "tmp/wanted"
* middle
	*< middle left
		* left
	*> middle right
		* right
@endmindmap
```

**Comment by arnaudroques** [comment] 2019-03-02 14:04
@pinage404 Thanks for your last "bubble" report. It's fixed in last beta http://beta.plantuml.net/plantuml.jar

**Comment by arnaudroques** [comment] 2019-03-03 12:57
In last beta http://beta.plantuml.net/plantuml.jar we have removed support for "number" and bracket "<" ">".
It was indeed too cryptic. Do you agree ? The trade-off between compacity and readability is not easy to find.

To choose between left and right you can now have:

```
@startmindmap
* count
** 100
*** 101
*** 102
** 200

left side

** A
*** AA
*** AB
** B
@endmindmap
```

Note that you can also use `right side` to update the right side. 
Actually any sentence containing left/right will do the job. In the final version, we'd like to have a unique sentence. But we are out of inspiration here so your ideas are welcome :-)

**Comment by mlopezgva** [comment] 2019-03-06 09:46
You can "borrow" the activity syntax here, just to make it feel like part of the PlantUML syntax family. :smile:

```
@startmindmap

* count
** Init
*** More
*** even more

split left
** Another
*** Branch
*** Here

split right[ again]
** Second thoughts
*** Keep dreaming

split left[again]
**** Time to end daydreaming
**** And start minding

@endmindmap
```

**Comment by pinage404** [comment] 2019-03-06 22:19
> The trade-off between compacity and readability is not easy to find.

I will always prefer readability to compacity.

Currently, octets are cheaper than my salary, so the time I spend reading and understanding the code is more expensive than the cost of using more octets.

So I prefer, by far, the readability

**Comment by TarasMazepa** [comment] 2019-06-11 00:09
Any chance to get ability to mark some mind map items with colors? So result will look like this? 
![Screen Shot 2019-06-10 at 5 08 33 PM](https://user-images.githubusercontent.com/6552358/59234600-7414e500-8ba2-11e9-8f0f-71a6a3c76023.png)

**Comment by arnaudroques** [comment] 2019-06-11 07:21
The most difficult part is to find a nice syntax. Any suggestion ? Thanks!

**Comment by 1kakarot** [comment] 2019-06-11 09:27
How about org-mode syntax but using a positioning (left or right) indicator at the end of line?
```
@startmindmap "OrgMode"
* Linux
** NixOS -R
** Debian -L
*** Ubuntu
@endmindmap
```

Perhaps one could use a level indicator 1, 2, ..., n that would declare the order like this:
```
@startmindmap "OrgMode"
* Linux
** NixOS -R
** Debian -2L
** Ubuntu -1L
@endmindmap
```
in order to make "Ubuntu" show above "Debian" without manual rearrangement of the text.

**Comment by TarasMazepa** [comment] 2019-06-11 17:20
```
@startmindmap

BackgroundColor<< RedType >> Red

* Pill
**[#blue] Blue part
**<< RedType >> Red part

@endmindmap
```

Either `[#blue]` or `BackgroundColor<< RedType >> Red` with `<< RedType >>` will work for me. But I haven't done much plantuml stuff, so do not know if there is better options available in other diagrams. `[#blue]` will work on the spot and will do the trick but it would not be best choice as it will only apply to the background, but some people can think it could be applied to other parts (text color or link color or border color. `BackgroundColor<< RedType >> Red` with `<< RedType >>` will allow to add support of styling other parts in the future, so this could be the ultimate option. 


So from my POV having support for `skinparam` in mindmaps will be the best thing to do, as people more or less already familiar with it. And it provides quite flexible way of styling mindmaps

**Comment by arnaudroques** [comment] 2019-06-11 17:55
Ok, so with last beta http://beta.plantuml.net/plantuml.jar you can now have :

@startmindmap
```
skinparam backgroundColor #EEEBDC
skinparam monochrome true
skinparam handwritten true
skinparam shadowing false
skinparam dpi 300

* root
** first
**[#AAA] second
```
@endmindmap

The support for skinparam is partial : there are no specific setting for MindMap for color, fonts...
The idea of using `<< stereotype >>`  is good : we'll keep it for latter when skinparam will be fully supported.

Right now, we are out-of-inspiration for naming mindmap setting for skinparam, so your ideas are welcome :-)

**Comment by cenggel** [comment] 2019-07-17 06:57
@arnaudroques 

> Ok, so with last beta http://beta.plantuml.net/plantuml.jar you can now have :
> 
> @startmindmap
> 
> ```
> skinparam backgroundColor #EEEBDC
> skinparam monochrome true
> skinparam handwritten true
> skinparam shadowing false
> skinparam dpi 300
> 
> * root
> ** first
> **[#AAA] second
> ```
> 
> @endmindmap
> 
> The support for skinparam is partial : there are no specific setting for MindMap for color, fonts...
> The idea of using `<< stereotype >>` is good : we'll keep it for latter when skinparam will be fully supported.
> 
> Right now, we are out-of-inspiration for naming mindmap setting for skinparam, so your ideas are welcome :-)

How to change the text color ?

**Comment by pinage404** [comment] 2019-07-20 17:38
Hi =)

sometimes i have node in wich i want to write a long text
this results in really huge diagram

of course, i can explicit split with a `\n` new line

but it could be cool if PlantUML was able to split long lines, maybe with an option who specify the maximum width of a node

![long lines](https://user-images.githubusercontent.com/6325757/61582006-c80dd480-ab25-11e9-981d-95020de989cd.png)

```plantuml
@startmindmap "long lines"
* Hi =)
	* sometimes i have node in wich i want to write a long text
		* this results in really huge diagram
			* of course, i can explicit split with a\nnew line
			* but it could be cool if PlantUML was able to split long lines, maybe with an option who specify the maximum width of a node
@endmindmap
```

**Comment by arnaudroques** [comment] 2019-07-21 11:59
Good idea !
Independently of your request, there is an ongoing process to enhance PlantUML thought styles (see http://wiki.plantuml.net/site/style-evolution )
MindMap diagram have been selected as testing area for this new style evolution, so we have integrated your request there.
So with last beta http://beta.plantuml.net/plantuml.jar you can have for example :

```
@startmindmap

style mindmapDiagram && node {
    Padding 12
    Margin 3
    HorizontalAlignment center
    LineColor blue
    LineThickness 3.0
    BackgroundColor gold
    RoundCorner 40
    WrapWidth 100
}

style mindmapDiagram && firstNode {
    LineStyle 8.0;3.0
    LineColor red
    BackgroundColor white
    LineThickness 1.0
    RoundCorner 0
    Shadowing 0.0
}

style mindmapDiagram && leafNode {
    LineColor gold
    RoundCorner 0
    Padding 3
}

style mindmapDiagram && arrow {
    LineStyle 4
    LineThickness 0.5
    LineColor green
}

* Hi =)
	* sometimes i have node in wich i want to write a long text
		* this results in really huge diagram
			* of course, i can explicit split with a\nnew line
			* but it could be cool if PlantUML was able to split long lines, maybe with an option who specify the maximum width of a node

@endmindmap
```

Is this what you were looking for ?
You can [also join the discussion here](https://join.slack.com/t/plantuml/shared_invite/enQtNjkwNzEyNTE5NzM1LTJmZjAyN2M4MmNhMDVkNzBlYmYwYzk5ZTVkYzQ0MzcxYTg2YzdhM2RhMTk3YzAxZDdmOGIwNmM5NmE0YzUxZTg)

**Comment by pinage404** [comment] 2019-07-21 12:18
```
style mindmapDiagram && node {
    WrapWidth 100
}
```

this is what was looking for ! =)

---

With this version, the link are default in red instead of blue in the previous version

**Comment by ajparkme** [comment] 2019-07-28 18:54
I know this might be diverting from the essence of mind mapping, but is there any way a "merge" might be able to be modelled? Here is a mockup of what I mean

![image](https://user-images.githubusercontent.com/38988995/62011468-9a9dd800-b170-11e9-966d-283adf583247.png)

Guessing the syntax _might_ be acheved something like this, seeing you removed the support for ">" brackets, which look more like merges to me...  ;)
```
@startmindmap
* 1
** 2.1
** 2.2
>* 3
@endmindmap
```

**Comment by pinage404** [comment] 2019-07-29 22:30
It could be interesting (but not a real mindmap anymore)

What should be the behavior / render for this : 

Multiple merged "leaves"

```plantuml
@startmindmap
* 1
** 2.1
** 2.2
** 2.3
** 2.4
>* 3
@endmindmap
``` 

Leaf in another level of the merge

```plantuml
@startmindmap
* 1
** 2.1
** 2.2
*** 2.2.1
>* 3
@endmindmap
``` 

Branches merge ?

```plantuml
@startmindmap
* 1
** 2.1
*** 2.1.1
** 2.2
*** 2.2.1
>* 3
@endmindmap
```

Leaves merge ? (there is two `*` in the last line)

```plantuml
@startmindmap
* 1
** 2.1
*** 2.1.1
** 2.2
*** 2.2.1
>** 3
@endmindmap
```

**Comment by ajparkme** [comment] 2019-07-30 00:43
```
@startmindmap
* 1
** 2.1
** 2.2
** 2.3
** 2.4
>* 3
@endmindmap
```
Your first example above is the only one that I think would work...

![image](https://user-images.githubusercontent.com/38988995/62089732-0a3fc000-b262-11e9-85ff-2f12b5a01115.png)

Otherwise, the merges become impossible to render.

I am suggesting that the same "rules" already in position for travelling "outward" to form new branches simply work in reverse - so the only way I can see it working is if a merge flows back to only one "node" (if that is the correct term), and that it is to the level immediately "below" the current level.

Therefore, all the other examples you gave would break this "tree in reverse" rule. The breaking of the "tree in reverse" rule would render the same problem as this, which you already account for:
```
@startmindmap
* 1
** 2.1
** 2.2
**** 4
@endmindmap
```
which yields the error
![image](https://user-images.githubusercontent.com/38988995/62090944-a966b680-b266-11e9-8a40-546e1c2a2d2d.png)

As an alternative to your  second example, a similar rendition, which does not break the rules, would be like this:

```
@startmindmap
* 1
** 2.1
** 2.2
>*3
** 2.2.1
@endmindmap
```
![image](https://user-images.githubusercontent.com/38988995/62090629-943d5800-b265-11e9-9f94-aec6b4fb5aca.png)

**Comment by ajparkme** [comment] 2019-07-30 01:09
OK, so I was trying to create a more interesting example right now, but came across another limitation. I wanted to render the following:
![image](https://user-images.githubusercontent.com/38988995/62092064-b89c3300-b26b-11e9-827e-70830881f7d8.png)
but I was breaking my own "tree in reverse" rule over on the merge to "3" on the right side, leaving 2.3 orphaned.

Correctly, I should do something like this:
![image](https://user-images.githubusercontent.com/38988995/62092402-ef267d80-b26c-11e9-9ce5-a67354feac94.png)

which could be coded like this:
```
@startmindmap
* 1
** 2.1
** 2.2
>*3
start left
** 2.1L
** 2.2L
** 2.3L
*** 3.1L
*** 3.2L
*** 3.3L
<** 4L
@endmindmap
```
unless of course there were a way to explicitly state that a node could be "orphaned" in a merge.
Hmmm...  this all feels like it is getting too complicated again!!!

But I like the _idea_ of trying to merge thoughts together in a mind map...! It's the kind of thing we can all do on paper, and in our heads easily enough... like coming to a conclusion from a number of different, but related thoughts...

**Comment by lockywolf** [comment] 2019-10-10 06:30
Would it be possible to make vertical mind maps?

Actually, I use the MindMap feature to draw trees when debugging (lisp) programs, and it is a HUUUGE help. The only thing that bothers me is that the trees are horizontally aligned. Which is fine if a datum in every node is short. (actually even look better this way), but not as good if the data are long strings. 

Anyway, thanks for your awesome work. PlantUML is such a great help.

**Comment by aadrian** [comment] 2019-10-10 07:47
> Would it be possible to make vertical mind maps?

@lockywolf could you give a visual example?

**Comment by lockywolf** [comment] 2019-10-15 06:00
![image](https://user-images.githubusercontent.com/2077025/66804094-23e4cf80-ef54-11e9-9643-f8d0157be691.png)
@aadrian

**Comment by aadrian** [comment] 2019-10-15 21:11
@lockywolf what about http://plantuml.com/wbs-diagram ?

**Comment by lockywolf** [comment] 2019-10-19 07:20
@aadrian can it grow up?

**Comment by hallvard** [comment] 2019-10-24 12:20
Could we support more ad-hoc links across branches, e.g use **"a long sentence" as id** to assign an identifier to a node and then allow links ala other diagrams at the end, e.g **--> id**

**Comment by b0g3r** [comment] 2019-10-28 21:19
It sounds strange, but plantuml 2019.11 and neither beta version doesn't support coloring nodes/edges for mindmaps. 

For example
```puml
@startmindmap
*[#Orange] Teamlead Roadmap
**[#FFBBAA] ABC
***[#FFBBCC]_ Resource Manager
@endmindmap
```

Now generates image like this:
![image](https://user-images.githubusercontent.com/19777948/67718565-13673700-f9e1-11e9-96da-ca3541c350af.png)

Unfortunately, I don't read and write on Java well, and couldn't find code which responsible about color, only this piece:
https://github.com/plantuml/plantuml/blob/82b570d0f0907ce1e99412594f5a6ff583631d20/src/net/sourceforge/plantuml/mindmap/MindMapDiagram.java#L137-L139

Any ideas about how to add color support to mindmaps? 🤔 

P.S. Also I found a [strange blog post](http://hangaroundtheweb.com/2019/07/mind-maps-in-spacemacs/#orgd158e08) about emacs plantuml plugin and there coloring described as an implemented feature

**Comment by arnaudroques** [comment] 2019-10-28 21:33
Thanks for the feedback.
It sounds like a regression : we are going to investigate.
We'll post a message here when this will be fixed.

**Comment by arnaudroques** [comment] 2019-11-03 17:41
The color regression is fixed in last release V1.2019.12

**Comment by b0g3r** [comment] 2019-11-04 09:11
How to change edge width in mindmap?

**Comment by s-kramer** [comment] 2019-11-10 15:38
Would you consider giving an option to write the text on the edges between the nodes instead of the nodes?

**Comment by nicph** [comment] 2020-02-19 12:46
Hi

I was trying to style an entire branch of a mindmap, using the "descendant" pseudo selector like described in http://wiki.plantuml.net/site/style-evolution , but that doesn't seem to work with mindmaps (planuml 1.2020.01)

```
@startmindmap
<style>
mindmapDiagram {
  .myStyle * {
    BackGroundColor lightblue
    LineColor lightblue
  }
}
</style>
* root
** node 1 <<myStyle>>
*** subNode 1
*** subNode 2
**** subSubNode

** node 2
@endmindmap


```

Here is what i get :

![whatiget](https://user-images.githubusercontent.com/824308/74834990-cbb44480-531c-11ea-9237-7732f46ddf4c.png)

And what i expected :

![expected](https://user-images.githubusercontent.com/824308/74835014-da9af700-531c-11ea-9785-eab5b214d209.png)


Am I missing something ?

By the way, is there any way to style the edge between two given node ? for example here between `root` and `node 1`, idealy with a dynamic selectors ?

**Comment by NielsKruse** [comment] 2020-03-21 13:33
Hi,
I am trying to, somehow, style the non-boxed nodes in a mindmap (the ones with underscores, i.e. "**_" - I'm not even sure if they have a specific name), but haven't found anything. They remain black. I tried various styles tag entries and skinparams.
Is that even possible?

**Comment by lrosenthol** [comment] 2020-03-25 13:52
Maybe I am missing this, but I can't seem to add a `note` to a node in a mindmap.  I want to put some comments/notes to the right/left of the nodes like I can in other types of diagrams.  Thanks for all the great work so far!!

**Comment by kishcs** [comment] 2020-04-23 03:31
This can be an inspiration.
[Miro Mindmap](https://www.mindmapsoft.com/wp-content/uploads/2019/08/10-Miro.jpg)

**Comment by sxiii** [comment] 2020-08-25 16:07
Greetings dear developers and vibrant community!

I am trying to use mindmap option to build a dark-themed mindmap. For this, I need the *_ ("no-box") objects to have FontColor white. However, when I am trying to describe a class with this fontcolor, it does not work.

P.S. I don't care if the whole text in document will be painted in white - it's okay for me. I just want a solution for dark-themed mindmaps. Here's an example code:
<details><summary>Example code</summary>
<code>
@startmindmap
skinparam defaultFontSize 18
skinparam defaultFontName Ubuntu
skinparam dpi 300
skinparam backgroundColor #302934
<style>
mindmapDiagram {
  .rootStyle * {
    BackGroundColor lightblue
    LineColor lightblue
  }
  .leafStyle * {
    LineColor lightgray
    FontColor white
  }
}
</style>
* Lessons by Den <<rootStyle>>
** OS-agnostic package management
***_ Flatpak <<leafStyle>>
***_ SNAP Packages <<leafStyle>>
***_ AppImages <<leafStyle>>
@endmindmap
</code>
</details>

That's the resulting image:
![image](https://user-images.githubusercontent.com/575925/91199100-b241ea00-e6fd-11ea-9578-42080566b250.png)

So I want the "Flatpak" and other "leaves" to be white font.

Thanks for your help!

**Comment by arnaudroques** [comment] 2020-08-25 17:12
@sxiii Thanks for the report. This is indeed a bug which is fixed in last beta http://beta.plantuml.net/plantuml.jar

**Comment by sxiii** [comment] 2020-08-25 17:29
Oh thank you @arnaudroques this is really fixed and works! For those who want to use the older version meanwhile, I just found a temporary fix for this issue. It's not pretty but it works - just color a text you need like that:
```
+++_ <font color="white">SNAP Packages
```
And it ensures that the text will be white. The problem with this solution is, obviously, that you have to type it in each and every row. I don't know if it can be build as a class and used everywhere. But better just use the beta as @arnaudroques suggested and you'll be all good!
<details><summary>Resulting image with beta</summary>
![latest](https://user-images.githubusercontent.com/575925/91207617-52e9d700-e709-11ea-8ab2-9a689cf3fe4a.png)
</details>

**Comment by stefan-m-lenz** [comment] 2020-10-27 14:58
Would it be possible to add a heading to a node in the mindmap?
For me this is one of the most important features of a mindmap that I have a heading and further content in the node.

**Comment by user1095108** [comment] 2020-12-28 14:04
I want a top-down mind-map, please.

**Comment by kk6mrp** [comment] 2021-05-19 04:01
> But I like the idea of trying to merge thoughts together in a mind map...! It's the kind of thing we
> can all do on paper, and in our heads easily enough... like coming to a conclusion from a number of 
> different, but related thoughts...

This would be awesome! I've been making a water flow diagram for work and the Mindmap style works super well for mapping out water flow. The only issue is that I can't merge water sources back together again as they would in a drainage system.

**Comment by johny-tee** [comment] 2023-04-13 19:06
Have you tried "top to bottom direction"? Works for me.

@startmindmap

**top to bottom direction**

* Debian
** Ubuntu
*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDE Neon
** LMDE
** SolydXK
** SteamOS
** Raspbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio
@endmindmap

**Comment by lockywolf** [comment] 2023-04-18 08:42
Seemingly, can be closed? 

Although, maybe support for four-directional diagrams could make PlantUML even more perfect...

But that is perfectionism really.

**Closed** 2023-04-18 08:48 UTC
Labels: enhancement, t:discussion
