### ISSUE TITLE
Activity Diagram: Style of multiline Box

### ISSUE THREAD

**Issue by AndreasMatthias** [plantuml/plantuml#1697] opened 2024-02-23 19:05 UTC
```plantuml
@startuml
<style>
.procedure {
   BackgroundColor #lightblue
}
</style>
start
: foo; <<procedure>>
: bar
  bar
  bar; <<procedure>>
: xox\nxox\nxox; <<procedure>>
stop
@enduml
```

![activity](https://github.com/plantuml/plantuml/assets/1072202/91d7d0ec-0e90-4688-a248-c5da012b2a99)

All 3 procedure boxes should have the same style, but the style is not applied onto the second box.

[Example on Online Server](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuR8fBgdCIRNZqYieoazEJIajIbMevb9GS4fCpauloY_DIt7EpyalKb3EoKpFA4dAAKtbgkMoqOTg0fl2PQMGbfzlhM1Z0pV2pWuec9HOnAM0834LLEHNnEJ127JfufBy0Yw7rBmKe2C1)

**Comment by The-Lum** [comment] 2024-02-25 17:26
Hi @AndreasMatthias,

Thanks for the report;
See similar issue/request here:
- #1534

Regards,
Th.

**Comment by The-Lum** [comment] 2024-02-25 17:33
Duplicate of #1534

**Comment by arnaudroques** [comment] 2024-02-26 21:53
Thanks for the report.
This should be fixed with last snapshot.
Please reopen this issue if needed.

**Closed by arnaudroques** 2024-02-26 21:53 UTC
Labels: duplicate

**Comment by AndreasMatthias** [comment] 2024-02-26 22:33
Works very well. Thank you.
