### ISSUE TITLE
Invalid activity diagram failing with internal exception

### ISSUE THREAD

**Issue by t-8ch** [plantuml/plantuml#372] opened 2020-09-17 09:31 UTC
The following minimal example of an activity diagram fails:

```
@startuml
:a:-->(b\n - c)
@enduml
```

With the following error:

```
java.lang.UnsupportedOperationException: net.sourceforge.plantuml.ugraphic.color.HColorNone$1: net.sourceforge.plantuml.ugraphic.color.HColorNone$1@5ffead27
	at net.sourceforge.plantuml.svek.image.Footprint$MyUGraphic.apply(Footprint.java:100)
	at net.sourceforge.plantuml.skin.VisibilityModifier.drawInternal(VisibilityModifier.java:113)
	at net.sourceforge.plantuml.skin.VisibilityModifier.access$000(VisibilityModifier.java:56)
	at net.sourceforge.plantuml.skin.VisibilityModifier$2.drawU(VisibilityModifier.java:105)
	at net.sourceforge.plantuml.ugraphic.ULayoutGroup.drawU(ULayoutGroup.java:60)
	at net.sourceforge.plantuml.cucadiagram.MethodsOrFieldsArea.drawU(MethodsOrFieldsArea.java:295)
	at net.sourceforge.plantuml.cucadiagram.BodyEnhanced.drawU(BodyEnhanced.java:265)
	at net.sourceforge.plantuml.svek.image.Footprint.getEllipse(Footprint.java:167)
	at net.sourceforge.plantuml.ugraphic.TextBlockInEllipse.<init>(TextBlockInEllipse.java:62)
	at net.sourceforge.plantuml.svek.image.EntityImageUseCase.calculateDimension(EntityImageUseCase.java:114)
	at net.sourceforge.plantuml.svek.Node.<init>(Node.java:98)
	at net.sourceforge.plantuml.svek.Bibliotekon.createNode(Bibliotekon.java:63)
	at net.sourceforge.plantuml.svek.GeneralImageBuilder.printEntity(GeneralImageBuilder.java:543)
	at net.sourceforge.plantuml.svek.GeneralImageBuilder.printEntities(GeneralImageBuilder.java:534)
	at net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:408)
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:112)
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:77)
	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:654)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:189)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:140)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagramsCuca(PSystemUtils.java:233)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:89)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:160)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:526)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:410)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:377)
	at net.sourceforge.plantuml.Run.main(Run.java:192)
```

tested on 1.2020.16 (git 2184f18c50e5e , dot - graphviz version 2.38.0 (20140413.2041) ) and 1.2020.17beta5 ( http://www.plantuml.com/plantuml/png/SoWkIImgAStDuR9AjDBLjTD8YibJq5L8rkHoICrB0Oa30000 )

**Comment by arnaudroques** [comment] 2020-09-17 21:09
The crash is fixed in last beta http://beta.plantuml.net/plantuml.jar

However, I'm not sure that the issue is completely fixed. Tell us what you think about it.
Thanks!

**Comment by t-8ch** [comment] 2020-09-18 07:31
Thanks for the quick response!

Looks good to me. Also works with my internal, more complex diagram.

**Closed** 2021-03-01 11:13 UTC
