### ISSUE TITLE
Tables rendering bug

### ISSUE THREAD

**Issue by MOZGIII** [plantuml/plantuml#49] opened 2017-03-29 13:23 UTC
I updated plantuml to version 2017.08 and with new plantuml my tables are rendered incorrectly.

I have the following code:
```pu
@startuml
state X
note right of X #FFF
|= header 1 |= header 2 |= header 3 |
| //A// | abc | def |
| //B// | qwe | |
end note
@enduml
```

I expect to have this kind of render (like it used to be): 
![image](https://cloud.githubusercontent.com/assets/265507/24456350/6ca62b9c-149b-11e7-9905-71966a83c0d8.png)

But the last version renders tables incorrectly:
![image](https://cloud.githubusercontent.com/assets/265507/24456392/91af1f98-149b-11e7-84f9-9bc48b044b5d.png) (it's a ascreenshot)

It is clearly a regression since the version I used before. Unfortunately I don't know what version I was using.

**Comment by arnaudroques** [comment] 2017-03-29 13:31
Are you sure that you are using version 2017.08 ?
The only server seems to works fine with your example:
http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuG8oIb8L8hZoye5KKMPwHeb2Vff2X8AocviRLusjGaPgOafgaOAX0e9jXCGsLgZXgb7GrtVKrrUeKKXCIWQIAQbfK54di6XXUIgGhE5ApKjH05d3vG1a0Uq60000

**Comment by MOZGIII** [comment] 2017-03-29 13:39
I'll double checked. Well, it seems like it's something with my setup. Rendered the whole thing from the command line and it worked.
I'm using Arom plugin to work on diagrams, which uses internally node-plantuml. It happened immediately after I downloaded the update from http://plantuml.com/download (chose latest version there), set `PLANTUML_HOME` to latest jar location and restarted Atom.
I'll have to dig deeper to figure out what's causing this.

**Comment by arnaudroques** [comment] 2017-03-29 13:43
Maybe Atom is adding some \n or \r somewhere.
The diagram looks rendered as:

```
@startuml
state X
note right of X #FFF

|= header 1 |= header 2 |= header 3 |

| //A// | abc | def |

| //B// | qwe | |

end note
@enduml
```

**Comment by MOZGIII** [comment] 2017-03-29 13:47
Yeah, probably it's the Atom plugin that breaks stuff. Going to ping them, thanks.

**Comment by arnaudroques** [comment] 2017-04-04 14:41
We have found a bug in plantuml.jar 2017.08 that may explain this behaviour.
Can you try last beta (beta21) to check the issue is solved ?
https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0
Thanks

**Comment by MOZGIII** [comment] 2017-04-04 16:59
I'll do it tomorrow.

**Comment by The-Lum** [comment] 2023-01-18 16:34
Hi all,

_[This is an Issue Review]_
This is now fixed:
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuG8oIb8L8hZoye5KKMPwHeb2Vff2X8AocviRLusjGaPgOafgaOAX0e9jXCGsLgZXgb7GrtVKrrUeKKXCIWQIAQbfK54di6XXUIgGhE5ApKjH05d3vG1a0Uq60000)](https://www.planttext.com/?text=SoWkIImgAStDuG8oIb8L8hZoye5KKMPwHeb2Vff2X8AocviRLusjGaPgOafgaOAX0e9jXCGsLgZXgb7GrtVKrrUeKKXCIWQIAQbfK54di6XXUIgGhE5ApKjH05d3vG1a0Uq60000)

- Thanks @MOZGIII for the report.
- Thanks PlantUML team for your work.

Regards.

**Closed by The-Lum** 2023-01-18 16:34 UTC
