### ISSUE TITLE
Alternative layout engines from graphviz

### ISSUE THREAD

**Issue by xeruf** [plantuml/plantuml#1110] opened 2022-09-02 11:52 UTC
As mentioned in  #1078 it could be useful to support the different layout engines of graphviz: https://graphviz.org/docs/layouts/

Furthermore, the `plantuml -help` is a bit confusing, as it writes at the bottom:

> If needed, you can setup the environment variable GRAPHVIZ_DOT.

Without context, without links, I had no idea what to put into this variable until I found the relevant documentation days later: https://plantuml.com/graphviz-dot#fa6a5a3224d7da66

Related issues: https://github.com/plantuml/plantuml/issues/840 and https://github.com/plantuml/plantuml/issues/182

**Comment by mcraveiro** [comment] 2022-10-08 09:09
I am extremely interested in this feature as I am producing very large class diagrams at present. The fact that the classes and namespaces are laid out horizontally means the diagrams are harder to understand. It would be great if one could experiment with other types of layouts, particularly circo [1].

[1] https://en.wikipedia.org/wiki/Circular_layout

**Comment by xeruf** [comment] 2022-10-08 18:47
@mcraveiro yes :)
I recommend experimenting with alternative layout engines like elk for the meantime: https://plantuml.com/elk

**Comment by mcraveiro** [comment] 2022-10-08 19:30
Ah most interesting! Sadly when I try it I get:

```
java.lang.ClassNotFoundException: org.eclipse.elk.graph.util.ElkGraphUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at net.sourceforge.plantuml.elk.proxy.Reflect.callStatic(Reflect.java:129)
	at net.sourceforge.plantuml.elk.proxy.graph.util.ElkGraphUtil.createGraph(ElkGraphUtil.java:28)
	at net.sourceforge.plantuml.elk.CucaDiagramFileMakerElk.createFile(CucaDiagramFileMakerElk.java:366)
	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:620)
	at net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:188)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:135)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:179)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:209)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:93)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:186)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:518)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:401)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:368)
	at net.sourceforge.plantuml.Run.main(Run.java:203)
java.lang.IllegalArgumentException: java.lang.ClassNotFoundException: org.eclipse.elk.graph.util.ElkGraphUtil
```

I'll have a look for the missing jars.

**Comment by mcraveiro** [comment] 2022-10-08 19:33
Lol, should have read the docs more carefully :-) worked after installing the ELK jar [1].  Very interesting layout!

[1] http://beta.plantuml.net/elk-full.jar

**Comment by xeruf** [comment] 2022-11-28 16:16
You could also checkout some parameters mentioned in https://github.com/plantuml/plantuml/issues/261#issue-499386689

**Comment by BenceSzalai** [comment] 2023-01-13 18:55
[This is an Issue Review]

Duplicate of #60.

Based on that one this is not something on the roadmap of PlantUML.

Either way, any further discussion of the issue should be under #60, so it's all in one place.

**Closed by BenceSzalai** 2023-01-13 18:55 UTC
