### ISSUE TITLE
Max size for notes, similar to #35

### ISSUE THREAD

**Issue by noamtamim** [plantuml/plantuml#104] opened 2018-02-20 10:07 UTC
`skinparam maxMessageSize` doesn't affect notes. I can see why that may be -- people may want more control over note formatting.
Please add another param, maxNoteSize that would do the same for notes.

And I see that in #35 you wonder if this name is good. I'd say `wrapMessageWidth` (if measured in pixels) and/or `wrapMessageCols` (if measured in characters) are better, since this param doesn't limit the **size**, it just inserts line breaks.

**Comment by Sidetalker** [comment] 2018-02-20 12:53
I knew this project wasn't dead, good, thanks.

**Comment by arnaudroques** [comment] 2018-02-20 18:15
Not dead, but clearly overloaded :-)

Anyway, thanks for the suggested parameter name.
With last beta http://beta.plantuml.net/plantuml.jar you can now have:

```
@startuml
skinparam wrapWidth 100
component component1 [
   this is a very long component description
]
note left
   this is a very long note that show be wrapped
end note
@enduml

```
and also

```
@startuml
skinparam wrapMessageWidth 100
A->B:very long long long message name

@enduml
```
Note sure if we should have separate settings for notes, components...
So I let you guys talk about this (no time to think right now :-) )

**Comment by drboa** [comment] 2018-08-07 09:40
Wrap width doesn't appear to be working on notes or on components...

**Comment by arnaudroques** [comment] 2018-08-25 16:39
Could you give a non-working example ?
The following one is working for us:
http://www.plantuml.com/plantuml/uml/TOv12W8n34NtESK_mimDvXOkn4MSHbjiaz961szlwK9NGXOFyZwyhJitVvPC_P6qSkE2et4zfU0HwxBGRgMQYZg-jE9C03ocZd6CbxGtikdzvo18trkgdapfGceko7BpVyCfU6H7ZtRWAZEZIY3HCB-q3Hgb7m00

**Comment by drboa** [comment] 2018-08-28 10:37
I don't know if wrapWidth is meant to work on sequence diagrams (it would be extremely useful if it did...) but it doesn't do anything at the moment...

http://www.plantuml.com/plantuml/png/XOwn2i90343tV4KsfuABYqEfVeFGEVP2x-WrgRdKujzxAheA8JmUF9AkE9clSuOo9Ld8QCRDQEbJy8Y7FS0ffu6RzgpN8qREMQ5YqxHl_rKWweoMnkXmYQbW7S8xs-FFoYeZlcA0_dSsA1VPEMvg4wfWuTlACZ26HAFHN80bVAgkKlt-2G00

**Comment by arnaudroques** [comment] 2018-08-28 16:28
Thanks for the feedback.
It should be fixed in last beta http://beta.plantuml.net/plantuml.jar

**Comment by drboa** [comment] 2018-08-29 11:00
I've noticed with the beta that wrapWidth is not being applied to text in legends:

http://www.plantuml.com/plantuml/png/jOv12W8n303lUKK-87Znua5Mt-07wZQqmRGfQTR5txjb_O488Kno66Rg7ioN8j2VN5kmK72rq5QEdl5q111AL2EwDhXdxhXDm1VP-_SbMXD-_P7wRDoSjSAuzpV0JHzukE1LU2OyOoOH1QZgXCOf-t-YXdzax31jj1Jv0000

**Comment by arnaudroques** [comment] 2018-08-30 19:45
Yes, but maybe we should use a separate setting for legend: general wrapWidth (for message, notes...) should be different that wrapWidth for legend that can be as wide as the diagram itself.
Any though ?

**Comment by zimchaa** [comment] 2018-09-24 16:29
I'm not sure if it should, but wrapWidth doesn't seem to be working in Activity (Beta) for notes:

```
@startuml
skinparam wrapWidth 150

title: Note wrapWidth Test

start 
    :This is a very long process step;
    note: This is a very very long note
stop

@enduml
```
[PlantUML Link](https://www.plantuml.com/plantuml/img/NOwn3i9034FtV8K_0GQMO-aNTAh47D68dhZUHPS0ukyRke2mlFdPyc3EtHzh8RldgjnvnQkpNlBi2uwd0v5dBv8mDfUVQ19pehqDGYXDIpQ46K_fRvHMRz3Uhc86Sz7pZjMOIVXZluLF7AjDYGQfSnpR0000)

**Comment by arnaudroques** [comment] 2018-09-25 20:03
> I'm not sure if it should, but wrapWidth doesn't seem to be working in Activity (Beta) for notes:

Thanks for the report. This is fixed in last beta http://beta.plantuml.net/plantuml.jar

**Comment by zimchaa** [comment] 2018-09-26 11:36
> Thanks for the report. This is fixed in last beta http://beta.plantuml.net/plantuml.jar
This is amazing - not sure you're watching this but I've downloaded the beta and confirmed it sorted on Windows (7) (doesn't use GraphViz but: latest verstion).

[Note wrapWidth Test.txt](https://github.com/plantuml/plantuml/files/2419473/Note.wrapWidth.Test.txt)
![note wrapwidth test](https://user-images.githubusercontent.com/1307363/46077409-b4554400-c188-11e8-88d5-58e805f432ee.png)

**Comment by arnaudroques** [comment] 2018-11-19 20:33
Could you post a short snippet that shows the issue ?
Thanks

**Comment by jensborrmann** [comment] 2018-11-20 06:09
```
@startuml

state "a" as a
state "In my humble opinion this is definitively too long for a state name one liner and would benefit from wrapping" as b
a -right-> b

@enduml
```

**Comment by arnaudroques** [comment] 2018-11-21 20:52
Thanks your example.
This should be fixed in last beta http://beta.plantuml.net/plantuml.jar

```
@startuml
skinparam wrapWidth 150
state "a" as a
state "In my humble opinion this is definitively too long for a state name one liner and would benefit from wrapping" as b
a -right-> b
@enduml

```
Tell us if it's not working for you!

**Comment by jensborrmann** [comment] 2018-11-23 14:30
Thanks for fixing this. What I forget to include in my example is an additional setting: hideEmptyDescription, which seems to prevent the wrapping from happening:

```
@startuml
hide empty description
skinparam wrapWidth 150
state "a" as a
state "In my humble opinion this is definitively too long for a state name one liner and would benefit from wrapping" as b
a -right-> b
@enduml
```

**Comment by arnaudroques** [comment] 2018-11-23 22:08
Ok, your example should work with new beta http://beta.plantuml.net/plantuml.jar
Tell us if you find other issues!
Thanks

**Comment by Godsmith** [comment] 2019-01-04 10:22
Hi!

wrapWidth does not seem to be affecting descriptions in state diagrams. i.e. 

```
@startuml
skinparam wrapWidth 150
state "a" as a
State "b" as b
b: aaaaaaa bbbbbbbbbb ccccccccc ddddddddd eeeeeeeee ffffffffff ggggggggg hhhhhhhh
a -right-> b
@enduml
```

I know I can insert line breaks manually, but it is not really feasible in my current use case since I'm generating these diagrams from code.

**Comment by arnaudroques** [comment] 2019-01-04 11:34
Thanks again for the feedback.
It should be fixed in last beta http://beta.plantuml.net/plantuml.jar

**Comment by Godsmith** [comment] 2019-01-04 11:37
That was quick! Also, if you did not fix this simultaneously, it is not working for line labels in state diagrams either:

```
@startuml
skinparam wrapWidth 150
state "a" as a
State "b" as b
a -right-> b : aaaaaaa bbbbbbbbbb ccccccccc ddddddddd eeeeeeeee ffffffffff ggggggggg hhhhhhhh
@enduml
```

**Comment by arnaudroques** [comment] 2019-01-04 11:54
For some reason, we use a different setting for labels in arrow and lines:

```
@startuml
skinparam maxMessageSize 150
state "a" as a
State "b" as b
a -right-> b : aaaaaaa bbbbbbbbbb ccccccccc ddddddddd eeeeeeeee ffffffffff ggggggggg hhhhhhhh
@enduml
```

In your case, you could set both value (`maxMessageSize` and `wrapWidth`) to 150.

BTW we are not 100% satisfied with current names (`maxMessageSize` and `wrapWidth`), so any idea is welcome! (We will ensure ascending compatibility even if we change those names)

Hope this help!

**Comment by Godsmith** [comment] 2019-01-04 12:56
Awesome, thank you!

Naming really is the hardest problem in programming. If you don't need two separate parameters, perhaps it could be just maxTextWidth or wrapTextWidth? If you need separate parameters, perhaps maxLabelWidth and maxElementWidth? Not sure if there is some better terminology to use though.

**Comment by judebert** [comment] 2019-07-30 18:40
In class diagrams, long constructors get word-wrapped (thanks!), but I expected the visibility indicator (the green circle) to be aligned with the top of the block, and the wrapped parameters to be indented.

http://www.plantuml.com/plantuml/uml/LSwn2i90383X_PuYew93SHIH5dHr4iGnj846xt974j4YlhitgHr_lkLlpL7zdcAm6qj1nGGFnNBXmKVOD4te8vh1WL8MSqNdBF0A0AiT2_j-GSyIkVSJ9jh2yHThGCa-afwdKgNxHfM9lFl7wwoNuHrQag5UVG00

**Comment by arnaudroques** [comment] 2019-08-01 17:48
Last beta http://beta.plantuml.net/plantuml.jar should align visibility indicator on top.

**Comment by leilapearson** [comment] 2020-02-15 20:44
Could wrapwidth also apply to class names?

[Examples where this would be handy](http://www.plantuml.com/plantuml/uml/VPB1KXin38Rl-nGYmw5ajWpJErE670gNJWUkN1HRoQfuvQqbGtdxsbwQa49wiYHB-dvPlbB3P7aCtS2UOAHnJKbdnt5oWRfE7racJ3Z2SyBfcRqDyENYekjEilpAqSZ39eipZWAUr2MUZ9ze5L3rqoa6HktXL72aSkmIefnrhgR0ulAotJx8WnmaB00LvWRGdP3ulvWFqIwvTxH4EaLHNdDWUoa15qF0TKnuJC1oUNTGirm-o3zjvhJLsqurwx3tSUrxw7MCZste6qe4h80Gecn1QPueRjw-9nZzjdDOeS0jRCc03IosdG1cYsFXEWpX1LZK27sj_vdLm4Knbioo_TfahGjth-9-eB1fCZwQ_IO6tmgqLawOhBR55dAeTEGnhb-lUwXMeshb70vVC_vBdgkUI8zWclRQVQUdwzvzGNL3ZA67nNqp5ZjBWSM5x0ccH9zrZlL0WKOIm_G2kzZ8tWVQ-mDlXxrNDqzRAbQMWatAnjKpSeFKfRILi6MhKJ9tlZZhklfXNVkMYrKvggvlAUP9uLOs2TLITfOJrOllL81byWBqFTnR8h8UxaZPaxZwp5bPI4lx7vWUIyhhq3TH9pOC5NX5ulCO_W00)

``` plantuml
@startuml
hide members
hide circle

skinparam wrapwidth 200

!unquoted function descriptiveClass($alias, $name, $description)
class "==$name\n\n $description" as $alias 
!endfunction

!unquoted function crc($alias, $name, $responsibility, $collaboration)
class "==$name\n\n**Responsibility**\n$responsibility\n\n**Collaboration**\n$collaboration" as $alias 
!endfunction

class "==Book\n\n Here is a long section of descriptive text. Can I get it to wrap automatically instead of just continuing?" as book
class "==Shelf\n\n **Responsibility**\nHold books as part of a bookcase\n\n**Collaboration**\nBookcase, Book" as shelf
class "==Bookcase\n\n **Responsibility**\nHolds shelves\n\n**Collaboration**\nShelf" as bookcase

descriptiveClass(school, "School", "Schools include pre-schools, elementary schools, middle schools, high schools, colleges, universities, technical institutes, etc.")

crc(city, "City", "Groups Infrastructure", "Neighborhood, Street, Residence, Business, Park, School, Hospital")
@enduml
```

**Comment by cherub-i** [comment] 2021-06-01 15:07
When I position a note e.g. `left of test::member`, the `wrapWidth` is not enforced. 
It would be great, if this kind of note was included in the width controlling.

[Example](http://www.plantuml.com/plantuml/uml/JOynhiCm28PtJi41tl2MBfboYyuq9ebL6qT0r5PLxrxa3Cra2_5_7_zeJkfxBM3tB1ifLNmeRTUSVCNBFy1Ko0oTpTzGkTvO1pJNB0jy042QCnQU7H3HrsnOcYpOnyvFnvXCJLnRAPnYGzk-hF7ooTEzvAp0adhs1COsT_qm77eC4-uojxXR8bHUVu6ZRefGHqzaZB5nN1JDKb0w-6SOunV5lm00)

**Comment by fkleedorfer** [comment] 2022-08-23 09:24
It would be nice to have this in work breakdown structures, too!

**Comment by arnaudroques** [comment] 2022-08-26 16:21
Thanks for the report.

This has been fixed [in last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot)  and [on the online server](https://www.plantuml.com/plantuml/uml/JOynhiCm28PtJi41tl2MBfboYyuq9ebL6qT0r5PLxrxa3Cra2_5_7_zeJkfxBM3tB1ifLNmeRTUSVCNBFy1Ko0oTpTzGkTvO1pJNB0jy042QCnQU7H3HrsnOcYpOnyvFnvXCJLnRAPnYGzk-hF7ooTEzvAp0adhs1COsT_qm77eC4-uojxXR8bHUVu6ZRefGHqzaZB5nN1JDKb0w-6SOunV5lm00).

Tell us if you find other issues!

**Comment by fabolhak** [comment] 2022-12-22 12:48
@arnaudroques Thank you for providing the `wrapWidth` skin parameter :). Is it planned to also be able to use it in Activity Diagrams?

The following example does not wrap unfortunately:
```plantuml
@startuml
skinparam wrapWidth 100
:this is a very long long long long long activity description;
@enduml
```

**Comment by fabolhak** [comment] 2022-12-23 09:01
@The-Lum thank you for the quick response :)

**Comment by BenceSzalai** [comment] 2022-12-31 17:08
I am looking for a way to only enforce max width for notes.

Rationale: I'm working with class diagram, and for the classes the one line = one property/method is very important to have clear readability in the diagram. However notes typically contain longer text, without such positional meaning, so those would be best auto-wrapped to a certain width, without affecting the way classes are laid out. In fact I am happy with the layout of all drawing elements, only would like to maximise the width of notes.

@arnaudroques 
> Note sure if we should have separate settings for notes, components...

Certainly notes are very different from any other elements, so it would be great to have a width control for notes only! `wrapNoteWidth` would be incredibly useful!

**Comment by The-Lum** [comment] 2023-01-02 10:53
@BenceSzalai, @arnaudroques:

I just open this wanted request here:
- [QA-17215 - Allow 'MaximumWidth' and 'MinimumWidth' on all styles for all diagrams](https://forum.plantuml.net/17215/allow-maximumwidth-and-minimumwidth-all-styles-for-diagrams)

Regards.

**Comment by BenceSzalai** [comment] 2023-01-06 09:19
That's nice, but I'm afraid that supporting max-width for all elements is a much bigger work than just for notes, as the issue originally requested, and it is certainly better to have some useful features in a realistic time-frame than a huge, all-encompassing feature, that is so big it it may never get delivered eventually.

**Comment by arnaudroques** [comment] 2023-01-09 21:52
This should be fixed in V1.2023.0
Tell us if you find other issues!
Thanks

**Comment by BenceSzalai** [comment] 2023-01-10 17:14
Thanks! So for reference, to set minimum and maximum width of notes one can add this to the puml file:
```
<style>
note {
  MinimumWidth 100
  MaximumWidth 150
}
</style>
```
I've just tried and it works fine in Class diagrams. Great to have it!

Not sure why some things are controlled by `skinparam`-s and why some by an embedded `<style>`, but that's not really the topic here.

**Comment by The-Lum** [comment] 2023-01-22 20:22
Hi all,
>Not sure, maybe this issue can be closed now?

_[This is an Issue Review]_
This is now fully fixed and answered.
- Thanks @noamtamim for the first report.
- Thanks all other peoples for the exchange and comments.
- Thanks PlantUML team for your work.

Regards.

**Closed by The-Lum** 2023-01-22 20:22 UTC
