### ISSUE TITLE
Error during CI due to no permission for creating snapshot

### ISSUE THREAD

**Issue by albert-github** [plantuml/plantuml#1261] opened 2023-01-12 14:35 UTC
I was updating my forked plantuml repository and at that moment also the GitHub Actions kick in and they gave an error (see: 
https://github.com/albert-github/plantuml/actions/runs/3902924444/jobs/6666824048):
```
Create snapshot release
...
> Task :generateMetadataFileForMavenPublication
> Task :generatePomFileForMavenPublication

> Task :publishMavenPublicationToOSSRHRepository FAILED
FAILURE: Build failed with an exception.

* What went wrong:
9 actionable tasks: 3 executed, 6 up-to-date
Execution failed for task ':publishMavenPublicationToOSSRHRepository'.
> Failed to publish publication 'maven' to repository 'OSSRH'
   > Could not PUT 'https://oss.sonatype.org/content/repositories/snapshots/net/sourceforge/plantuml/plantuml/1.2023.1beta2-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 1s
Error: Process completed with exit code 1.
```

which is in my opinion logical as one just wants to have the snapshot for the master branch as updated by a maintainer.
In doxygen we ware creating internal documentation and publish it on the GitHub pages and this publishing should also only happen under the master / maintainer requirement.
Here we use the following code:
```
    - name: Publish Internal documentation to Github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: build/doxygen_docs/html
      if: ${{ github.event_name == 'push' && matrix.config.name == 'Ubuntu Latest GCC Release' }}
```
see also https://github.com/doxygen/doxygen/blob/master/.github/workflows/build_cmake.yml

note here the part `github.event_name == 'push'` (the "Ubuntu..." is there as we only generate the internal documentation through that part).

Probably the "push" would also work for plantuml.

**Comment by arnaudroques** [comment] 2023-01-12 15:04
I'm not comfortable with github action...

Do you think we should [change L175](https://github.com/plantuml/plantuml/blob/master/.github/workflows/ci.yml#L175) from:

`if: needs.workflow_config.outputs.do_release == 'true'`

to

`if: needs.workflow_config.outputs.do_release == 'true' && ${{ github.event_name == 'push' }}`

and also at a test [at line 108](https://github.com/plantuml/plantuml/blob/master/.github/workflows/ci.yml#L108) ?

@gliptak Any though?

**Comment by albert-github** [comment] 2023-01-12 15:19
I don't think line [L175](https://github.com/plantuml/plantuml/blob/master/.github/workflows/ci.yml#L175) should be changed but that the line `if: ${{ github.event_name == 'push' }}` should be added after [L160](https://github.com/plantuml/plantuml/blob/master/.github/workflows/ci.yml#L160) (and probably also be added after line [L171](https://github.com/plantuml/plantuml/blob/master/.github/workflows/ci.yml#L171))

**Comment by gliptak** [comment] 2023-01-16 22:17
@arnaudroques I recommend setting the target conditions while emitting the flags

https://github.com/plantuml/plantuml/blob/master/.github/workflows/ci.yml#L55
https://github.com/plantuml/plantuml/blob/master/.github/workflows/ci.yml#L62

@albert-github https://github.com/plantuml/plantuml/blob/master/.github/workflows/ci.yml#L53 indicates that (snapshot) release is enabled by design

**Comment by albert-github** [comment] 2023-01-17 09:55
I think it doesn't matter where to do the setting, maybe the place mentioned by @gliptak is even a bit better, though I think it might be good to place a small comment with lines L55 / L 62 / L160 / L171 to indicate the intention, especially as the comment L53 is "far away" from lines L160 / L171

**Comment by arnaudroques** [comment] 2023-01-17 18:07
So https://github.com/plantuml/plantuml/commit/c2bb4f8a37758c3f90dade8450c7b15ef83c5fc3 has been just commited.
Tell us if it helps!

**Comment by albert-github** [comment] 2023-01-17 18:10
I think it is working, see https://github.com/albert-github/plantuml/actions/runs/3941988678/jobs/6745195646

**Comment by arnaudroques** [comment] 2023-01-17 18:16
So I close the issue. Please re-open it if needed

**Closed by arnaudroques** 2023-01-17 18:16 UTC
