### ISSUE TITLE
Input size limit is 100k

### ISSUE THREAD

**Issue by trothwell** [plantuml/plantuml#548] opened 2021-05-07 04:27 UTC
There's an issue when the input size is greater than 100k.

Below I've created a reproduction test.
1. The first part will perform the compression directly and show the exception.
2. The 2nd will show what it looks like the user as it goes through the transcoder.

This commit is where the bug was introduced:
1. https://github.com/plantuml/plantuml/commit/e9fb57cbbedb86ab733aa3aa3104f2ecb4ec9250#r50498562

```java
  @Test
  public void bugReport() throws Exception {
    final Compression compression = new CompressionZlib();
    compression.decompress(compression.compress(repeat("x", 100_000).getBytes(UTF_8)));
    try {
      compression.decompress(compression.compress(repeat("x", 100_001).getBytes(UTF_8)));
      fail("Expected exception.");
    } catch (final NoPlantumlCompressionException e) {
      assertEquals(
          "net.sourceforge.plantuml.code.NoPlantumlCompressionException: Too big?", e.getMessage());
    }

    final Transcoder transcoder = TranscoderUtil.getDefaultTranscoder();
    transcoder.decode(transcoder.encode(repeat("x", 100_000)));
    try {
      transcoder.decode(transcoder.encode(repeat("x", 100_001)));
      fail("Expected exception.");
    } catch (final NoPlantumlCompressionException e) {
      // Different error because of the legacy fallback in "TranscoderSmart"
      assertEquals(
          "net.sourceforge.plantuml.code.NoPlantumlCompressionException: java.util.zip.ZipException: incorrect header check",
          e.getMessage());
    }

  static String repeat(final String s, final int times) {
    final StringBuilder sb = new StringBuilder();
    for (int idx = 0; idx < times; idx += 1) {
      sb.append(s);
    }
    return sb.toString();
  }
```

**Comment by trothwell** [comment] 2021-06-08 21:56
Can I get this issue confirmed by another?

**Comment by timchase01** [comment] 2022-04-20 19:30
I am running into the same issue.  Is there a fix for this??

net.sourceforge.plantuml.code.NoPlantumlCompressionException: net.sourceforge.plantuml.code.NoPlantumlCompressionException: java.util.zip.ZipException: incorrect header check
        at net.sourceforge.plantuml.code.TranscoderImpl.decode(TranscoderImpl.java:90)
        at net.sourceforge.plantuml.code.TranscoderSmart.decode(TranscoderSmart.java:67)
        at net.sourceforge.plantuml.servlet.PlantUmlServlet.getTextFromUrl(PlantUmlServlet.java:234)
        at net.sourceforge.plantuml.servlet.PlantUmlServlet.getText(PlantUmlServlet.java:181)
        at net.sourceforge.plantuml.servlet.PlantUmlServlet.doPost(PlantUmlServlet.java:154)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:694)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:777)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:355)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:866)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1708)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: net.sourceforge.plantuml.code.NoPlantumlCompressionException: java.util.zip.ZipException: incorrect header check
        at net.sourceforge.plantuml.code.CompressionHuffman.decompress(CompressionHuffman.java:78)
        at net.sourceforge.plantuml.code.TranscoderImpl.decode(TranscoderImpl.java:85)
        ... 28 more
Caused by: java.util.zip.ZipException: incorrect header check
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:165)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:123)
        at net.sourceforge.plantuml.code.CompressionHuffman.decompress(CompressionHuffman.java:69)
        ... 29 more

**Comment by timchase01** [comment] 2022-04-20 19:45
Just updated to latest 2.2022.4 release and it is fixed in that release.  thanks

**Comment by The-Lum** [comment] 2023-09-12 17:59
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @trothwell  for the report.
- Thanks @timchase01 for your answer.
- Thanks PlantUML team for your work.

Regards.

**Closed by The-Lum** 2023-09-12 17:59 UTC
