### ISSUE TITLE
Is there a way to disable Welcome message.

### ISSUE THREAD

**Issue by shd101wyy** [plantuml/plantuml#55] opened 2017-05-09 00:01 UTC
For example, when I created an empty diagram, it will show: 

![screen shot 2017-05-08 at 7 00 22 pm](https://cloud.githubusercontent.com/assets/1908863/25830165/9d105790-3420-11e7-8019-b65dbbd7c9c0.png)

Is there a way to remove the `Welcome` message?

Thank you :)

**Comment by arnaudroques** [comment] 2017-05-09 08:52
Hi,
Currently, you cannot remove it.
It should only be printed on empty/small diagram.
Is it a big issue ?
This message is intended to help people that discover PlantUML on first time.

BTW, the issue https://github.com/shd101wyy/markdown-preview-enhanced/issues/398 seems to be fixed now.

**Comment by aadrian** [comment] 2017-05-09 16:23
> Is it a big issue ?

It's still an issue, and the user first believes that it broke something. 
IMHO this message should be displayed only if it's called explicitly (e.g. by an API, or by some tool that integrates it).

> This message is intended to help people that discover PlantUML on first time.

It's not helping :) .

**Comment by arnaudroques** [comment] 2017-05-10 07:06
Would it be good if we add some flag -nowelcome in the command line ?

**Comment by aadrian** [comment] 2017-05-10 07:11
> Would it be good if we add some flag -nowelcome in the command line ?

Only if it's the other way around: a ```-welcome``` flag to display the welcome screen it only when the flag is active :) .

**Comment by VladimirAlexiev** [comment] 2017-09-07 18:10
@aadrian can you explain "the user first believes that it broke something"?
An empty diagram is a syntax error and the error is displayed, so what's the harm to also display the welcome/help?

**Comment by veponen** [comment] 2018-01-05 07:51
@VladimirAlexiev I have pretty much the same problem. I have a Jetty server and recently built plantuml.war file dropped in it. it works fine when using interactively. I am now trying to solve this with Postman-tool. 

Can you tell the url and the post parameter name of the to send to it to get a link for the png-file genearated? 

some public server url suits just fine, I can tune it to fit to my service. And also use the public server to verify.

**Comment by VladimirAlexiev** [comment] 2018-01-05 08:37
@veponen I don't understand the comment, is it for this issue? 
Basically, I agree with the author ArnaudRoques that this one is not a bug.

**Comment by veponen** [comment] 2018-01-05 08:49
@VladimirAlexiev . Yes, I agree now. when failing it gives this welcome message. So I am missusing plantuml.war. 
Is there any kind of integration guide, to integrate PlantUML to other tools?

**Closed** 2023-01-13 14:25 UTC
